GET http://localhost:7007/api/dogs
###

GET http://localhost:7007/api/dogs/1
###

POST http://localhost:7007/api/dogs/create
Content-Type: application/json

{
  "name": "V3",
  "breed": "V3",
  "age": 3,
  "gender": "MALE"
}
###

PUT http://localhost:7007/api/dogs/1/update
Content-Type: application/json

{
  "name": "V3",
  "breed": "V3",
  "age": 3,
  "gender": "MALE"
}
###

DELETE http://localhost:7007/api/dogs/1/delete
Content-Type: application/json
###