GET http://localhost:7007/api/vet/appointments
###

GET http://localhost:7007/api/vet/appointments/1
###

GET http://localhost:7007/api/vet/patients
###

GET http://localhost:7007/api/vet/patients/1
###

POST http://localhost:7007/appointments/create
Content-Type: application/json

{
  "id": 5,
  "description": "Test 1",
  "testDate": "Testing the date"
}
###

POST http://localhost:7007/api/vet/patients/create
Content-Type: application/json

{
  "id": 3,
  "allergies": "Test1",
  "medicine": "Test2"
}