### Henter alle hoteller
GET http://localhost:7007/api/hotels

### Henter et specifikt hotel udfra id'et
GET http://localhost:7007/api/hotels/21

### Henter et specifikt hotel ud fra id'ets værelser
GET http://localhost:7007/api/hotels/7/rooms

### Indsætter et nyt hotel ind i databasen
POST http://localhost:7007/api/hotels
Content-Type: application/json

{
  "name": "name",
  "address": "Test"
}

### Opdaterer et eksisterende hotels navn & adresse
PUT http://localhost:7007/api/hotels/12
Content-Type: application/json

{
  "name": "Bedste-hotel",
  "address": "Kongevejen"
}

### Sletter et hotel ud fra et specifikt id
DELETE http://localhost:7007/api/hotels/11

### Henter alle værelser
GET http://localhost:7007/api/rooms

### Henter et specifikt værelse ud fra id'et
GET http://localhost:7007/api/rooms/3

### Indsætter et nyt rum ind i databasen med et hotel
POST http://localhost:7007/api/rooms
Content-Type: application/json

{
  "number": 30,
  "price": 3000,
  "hotel": {
    "id": 16
  }
}

### Opdatere et eksisterende rum ud fra id'et
PUT http://localhost:7007/api/rooms/34
Content-Type: application/json

{
  "number": 30,
  "price": 4000
}

### Sletter et eksisterende rum ud fra id'et
DELETE http://localhost:7007/api/rooms/27

### Registrer en ny bruger
POST http://localhost:7007/api/auth/register
Content-Type: application/json

{
"username": "AhmadTest",
"password": "1234"
}

### Logger ind med en bruger
POST http://localhost:7007/api/auth/login
Content-Type: application/json

{
  "username": "AhmadTest",
  "password": "1234"
}

### Få adgang via Json Web Token
GET http://localhost:7007/api/protected/user_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJzdWIiOiIySGFubmkyMyIsImV4cCI6MTcxMDc4NzIyMiwicm9sZXMiOiIsdXNlciIsInVzZXJuYW1lIjoiMkhhbm5pMjMifQ.NG6F7M8KsH4X1hR1TyOao96MD4oTAWF91icZDoqadG4

### Få adgang via Json Web Token
GET http://localhost:7007/api/protected/admin_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJzdWIiOiJBaG1hZFRlc3QiLCJleHAiOjE3MTA3ODczNjIsInJvbGVzIjoiLGFkbWluIiwidXNlcm5hbWUiOiJBaG1hZFRlc3QifQ.IEV5M8Fi79eTcXOEgNWCd4fn5Ae064jlMSIurhD4-lU