### Henter alle hoteller
GET http://localhost:7007/api/hotels

### Henter et specifikt hotel udfra id'et
GET http://localhost:7007/api/hotels/7

### Henter et specifikt hotel ud fra id'ets værelser
GET http://localhost:7007/api/hotels/7/rooms

### Indsætter et nyt hotel ind i databasen
POST http://localhost:7007/api/hotels
Content-Type: application/json

{
  "name": "name",
  "address": "Test"
}

### Opdaterer et eksisterende hotels navn & adresse
PUT http://localhost:7007/api/hotels/6
Content-Type: application/json

{
  "name": "Bedste-hotel",
  "address": "Kongevejen"
}

### Sletter et hotel ud fra et specifikt id
DELETE http://localhost:7007/api/hotels/6

### Henter alle værelser
GET http://localhost:7007/api/rooms

### Henter et specifikt værelse ud fra id'et
GET http://localhost:7007/api/rooms/3

### Indsætter et nyt rum ind i databasen med et hotel
POST http://localhost:7007/api/rooms
Content-Type: application/json

{
  "number": 30,
  "price": 3000,
  "hotel": {
    "id": 16
  }
}

### Opdatere et eksisterende rum ud fra id'et
PUT http://localhost:7007/api/rooms/34
Content-Type: application/json

{
  "number": 30,
  "price": 4000
}

### Sletter et eksisterende rum ud fra id'et
DELETE http://localhost:7007/api/rooms/34
